// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZKar005xtb1o-hnW_0ZsA86YKBaFBmY',
    appId: '1:477580312539:web:3d6e8e138ab3e68a20f1fe',
    messagingSenderId: '477580312539',
    projectId: 'cmsc23-todo-app-jmcorcega',
    authDomain: 'cmsc23-todo-app-jmcorcega.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jmcorcega.appspot.com',
    measurementId: 'G-8F0T0J1SS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeXVKqc65OmMzgAB5i1vjeYNxdWiwoKg',
    appId: '1:477580312539:android:e5c71aecfcc218e320f1fe',
    messagingSenderId: '477580312539',
    projectId: 'cmsc23-todo-app-jmcorcega',
    storageBucket: 'cmsc23-todo-app-jmcorcega.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssJ2XTDiRKV-kIpbBK5NDUhs_gIbbL3M',
    appId: '1:477580312539:ios:5eb409a43516298b20f1fe',
    messagingSenderId: '477580312539',
    projectId: 'cmsc23-todo-app-jmcorcega',
    storageBucket: 'cmsc23-todo-app-jmcorcega.appspot.com',
    iosClientId: '477580312539-knrmn0vt5ros1p4p8lb2t2pofm8q616r.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBssJ2XTDiRKV-kIpbBK5NDUhs_gIbbL3M',
    appId: '1:477580312539:ios:5eb409a43516298b20f1fe',
    messagingSenderId: '477580312539',
    projectId: 'cmsc23-todo-app-jmcorcega',
    storageBucket: 'cmsc23-todo-app-jmcorcega.appspot.com',
    iosClientId: '477580312539-knrmn0vt5ros1p4p8lb2t2pofm8q616r.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
